#!/bin/sh
TARGET="`pwd`/plugins"
PLUGIN="WorldEdit"
URL=$1
VERSION=$2
TARGET_DATA="`pwd`/plugin-data/$PLUGIN"
mkdir -p $TARGET_DATA

TMP_TARGET=`mktemp -d`

./download -e zip -t "$TMP_TARGET" -O "worldedit.zip" "$PLUGIN" "$URL" "$VERSION"

cd $TMP_TARGET
unzip $TMP_TARGET/worldedit.zip
cp $TMP_TARGET/WorldEdit.jar $TARGET/$PLUGIN-v$VERSION.jar
cp -R $TMP_TARGET/craftscripts $TARGET_DATA
cd $TARGET/..

